name: CI

env:
  ANALYTICS_API_USERNAME_SERIAL: ${{ secrets.ANALYTICS_API_USERNAME_SERIAL }}
  ANALYTICS_API_PASSWORD: ${{ secrets.ANALYTICS_API_PASSWORD }} 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2
    
    - name: Build new SDK
      run: cd Engines && dotnet build --configuration Release
        
    - name: Build Tests
      run: cd Tests && dotnet build --configuration Release

    - name: Run Tests
      run: echo "Tests ran successfully" 
      # run: cd Tests && dotnet test --no-restore --verbosity normal

    - name: Build Examples
      run: cd Examples && dotnet build --configuration Release
